version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./site:/usr/share/nginx/html:ro
        links:
            - php
    php:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            # - ./php/php.conf:/usr/local/etc/php/conf.d/php.conf:ro
            - ./site:/usr/share/nginx/html:ro
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./data/mysql/mysql_sock:/var/run/mysqld
        links:
            - mysql:mysql
            - redis:redis
    mysql:
        build: ./mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/mysql/mysql_sock:/var/run/mysqld
        ports:
            - "3306:3306"
        environment:
            MYSQL_HOST: 127.0.0.1
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: redis:3.0
        ports:
            - "6379:6379"

